[I] Loading dataset SBM_CLUSTER...
train, test, val sizes : 10000 1000 1000
[I] Finished loading.
[I] Data load time: 13.4884s
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/p/psoga/benchmarking-gnns/main_SBMs_node_classification.py", line 68, in train_val_pipeline
    with open('./data/SBMs/train_SBM.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/SBMs/train_SBM.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/p/psoga/benchmarking-gnns/main_SBMs_node_classification.py", line 317, in <module>
    main()    
  File "/afs/crc.nd.edu/user/p/psoga/benchmarking-gnns/main_SBMs_node_classification.py", line 315, in main
    train_val_pipeline(MODEL_NAME, dataset, params, net_params, dirs)
  File "/afs/crc.nd.edu/user/p/psoga/benchmarking-gnns/main_SBMs_node_classification.py", line 77, in train_val_pipeline
    dataset._add_automaton_encodings(model.pe_layer.pos_transition, model.pe_layer.pos_initials[0])
  File "/afs/crc.nd.edu/user/p/psoga/benchmarking-gnns/data/SBMs.py", line 283, in _add_automaton_encodings
    with open('./SBMs/train_SBM.pkl', 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './SBMs/train_SBM.pkl'
